version: '3.8'

services:
  tvm-builder-gcc-simple:
    image: custler/tvm-builder-gcc-simple:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: tvm-builder-gcc-simple
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./data:/workspace/data
      - ./scripts:/workspace/scripts
    working_dir: /workspace/scripts
    environment:
      - TVM_HOME=/data/tvm
      - Host_BUILD=/data/tvm/build
      - Dev_BUILD=/data/tvm/build-riscv
      - ZSTD_LIB_DIR=/usr/lib/x86_64-linux-gnu
      - TOOLROOT=/opt/riscv
      - RISCV_CFLAGS=-march=rv64gcv0p7_zfh_xtheadc -mabi=lp64d -O3
      - JOBS=${JOBS}
      - TVM_VERSION=${TVM_VERSION}
    tty: true
    stdin_open: true
